### ISSUE TITLE
Withdraw team

### ISSUE THREAD

**Issue by ofu997** [Chingu-cohorts/voyage-wiki#263]
- Voyage number (5 or 6): 5
- Team Name: geckos team 12
- Slack Name: ofu997
- Timezone: utc-8

**_Issue Description & Expected Outcome:_** 
withdraw team due to lack of participation+progress.

**Comment by tropicalchancer** [comment]
Thanks for letting us know ofu997. 🙏

**Comment by HixOba** [comment]
Hi @tropicalchancer and @ofu997 Oliver, i know this has been closed. I note @ofu997 knows some React, any chance you might want to join me to complete the mostly frontend work remaining for our voyage 6 MVP?

**Comment by ofu997** [comment]
Hi @Hixsav. Sure, I could take a look.

**Comment by HixOba** [comment]
Hi Oliver

Thanks!

 I have done a lot of work for the backend to the web app which aims to
recreate socialcoder.org web app.

I am more of a backend person planning to use this to level up my React
frontend but now find i am not having a responsive frontend partner. I am
unable to explain what i need her to do in order to have a smooth so i had
to make a ticket/issue:

https://github.com/Chingu-cohorts/voyage-wiki/issues/272

Cheers
Obaye

**Comment by ofu997** [comment]
Hi Obaye,
I see you have 4 pages to render. 
I have worked a bit with React without using other stack techs. 
[Math game](https://codepen.io/ofu997/pen/oELRbx?editors=1010)
[(this was made with a react book)](https://s3-us-west-2.amazonaws.com/03-15-ofu/public/index.html)

I am in Portland, UTC-8.

**Comment by HixOba** [comment]
Hi Oliver

I see you have some nice numbers and mathematical bent, it would be
interesting to work together at some point i think.  I have a side project
where the "Timers" app functionality would work perfecto i think :)

But, have you looked at socialcoder.org yet? It is not so much much a
numbers thing but a regular web application with a mongodb-based backend i
have done. It has (or will have) a lot of pages to render i suspect.

Let me know

Cheers
Obaye

**Comment by ofu997** [comment]
I visited socialcoder. This is what you want to clone? I’d like to join and see what i can do.

**Comment by HixOba** [comment]
Yes. It is.
I have done a lot of the backend. Although i have run into rough weather
since this morning - the backend is no longer connecting to the mongodb
database so i am fighting that  fire right now.

I will ask @chance to hear what he has to say. Chingu will have the final
say.

**Comment by HixOba** [comment]
Hi Oliver

Are you on discord? We can chat on there, here is an invite

https://discord.gg/e9cYDY

I think it expires in 24 hours, if we dont get to chat before it expires
i'll simply generate another one. But let me know when you are able to chat.

Cheers
Obaye

**Comment by HixOba** [comment]
HI Oliver

I havnt heard from you in a while, whatsup?

Just to let you know, @chance has no beef about me having someone else work
with me to finish it, and ofcourse you will have the history showing who
has contributed. The ticket has now been formally closed because i asked
for it to be closed.

I have since updated things on the issues page of the workspace in github,
and have a pull request which i was hoping you would have a look at and
merge. But i may have to do it a little later this morning.

In the meantime, i have been using issue tickets on the repo to state what
needs doing.

Let me know and have a nice day!

Obaye
