### ISSUE TITLE
Need Access to Geckos-Team-18 GitHub

### ISSUE THREAD

**Issue by jasonmichaels** [Chingu-cohorts/voyage-wiki#289]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: geckos-team-18
- Slack Name: drunkenkismet
- Timezone: EST

**_Issue Description & Expected Outcome:_** Switched to (hopefully) the last/best team after a couple of false starts, but need access to the new team's GitHub

**_Symptoms:_** NA

**_Steps to Recreate:_** NA

**_Resolution:_** GitHub creds

**Comment by tropicalchancer** [comment]
Added.

**Comment by jdmedlock** [comment]
From a Slack conversation this morning...

drunkenkismet [1:36 AM]
Hey, @Jim -- are all team members supposed to have the same privileges to the GitHub repo? My two remaining, active teammates have access I don't seem to have, and it's creating headaches since since I have to basically fork everything. Thanks in advance for clarifying this for me!

**Comment by jasonmichaels** [comment]
Any word on this?
